version: '3.6'
services:
  
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  
  hasura:
    image: hasura/graphql-engine:v2.0.0-alpha.5
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file: .env
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=$HASURA_GRAPHQL_DATABASE_URL
      ## enable the console served by server
      - HASURA_GRAPHQL_ENABLE_CONSOLE=$HASURA_GRAPHQL_ENABLE_CONSOLE # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      - HASURA_GRAPHQL_DEV_MODE=$HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=$HASURA_GRAPHQL_ENABLED_LOG_TYPES
      ## uncomment next line to set an admin secret
      - HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_GRAPHQL_ADMIN_SECRET
      - DATA_ARM_APP_KEY=$DATA_ARM_APP_KEY

  zarya:
    build: ./zarya/
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    - ./error.log:/usr/src/app/error.log
    env_file: zarya/.env
    environment: 
      - HASURA_SECRET=$HASURA_SECRET
      - ENCRYPTION_KEY=$ENCRYPTION_KEY
    links:
      - hasura

volumes:
  db_data:

