version: '3.6'
services:

  db_keys:
      image: postgres:12
      volumes:
        - db_keys:/var/lib/postgresql/data
      env_file: .env
      environment:
        - POSTGRES_PASSWORD=$KEYS_PASSWORD
        - POSTGRES_DB=$KEYS_DB
        - POSTGRES_USER=$KEYS_USER

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      env_file: .env
      environment:
        - DB_VENDOR=POSTGRES
        - DB_ADDR=db_keys
        - DB_PASSWORD=$KEYS_PASSWORD
        - DB_DATABASE=$KEYS_DB
        - DB_USER=$KEYS_USER
        - KEYCLOAK_USER=$KEYCLOAK_USER
        - KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 9000:8080
      depends_on:
        - db_keys


  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  
  hasura:
    image: hasura/graphql-engine:v2.0.0-alpha.5
    ports:
    - "7000:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file: .env
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=$HASURA_GRAPHQL_DATABASE_URL
      ## enable the console served by server
      - HASURA_GRAPHQL_ENABLE_CONSOLE=$HASURA_GRAPHQL_ENABLE_CONSOLE # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      - HASURA_GRAPHQL_DEV_MODE=$HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=$HASURA_GRAPHQL_ENABLED_LOG_TYPES
      ## uncomment next line to set an admin secret
      - HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_GRAPHQL_ADMIN_SECRET

  zarya:
    build:
      context: ./zarya
      dockerfile: Dockerfile
      args:
        - HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_GRAPHQL_ADMIN_SECRET
        - ENCRYPTION_KEY=$ENCRYPTION_KEY
        - HASURA_APP_URL=$HASURA_APP_URL
    ports:
    - "8000:3000"
    volumes:
    - ./zarya:/app
    - ./error.log:/usr/src/app/error.log
    env_file: .env
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_GRAPHQL_ADMIN_SECRET
      - ENCRYPTION_KEY=$ENCRYPTION_KEY
      - HASURA_APP_URL=$HASURA_APP_URL
    depends_on:
      - 'hasura'

  astronaut:
    ports:
    - "3000:3000"
    depends_on:
      - 'hasura'
    env_file: .env
    volumes:
      - ./astronaut:/usr/src/app/astronaut
      - /usr/src/app/astronaut/node_modules
    build:
      context: ./astronaut
      dockerfile: Dockerfile
      args:
        - DISCORD_URL=$DISCORD_URL
        - BOT_NAME=$BOT_NAME
        - BOT_IMAGE_URL=$BOT_IMAGE_URL
    environment:
      - BOT_NAME=$BOT_NAME
      - DISCORD_URL=$DISCORD_URL
      - BOT_IMAGE_URL=$BOT_IMAGE_URL
volumes:
  db_data:
    driver: local
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local
  db_keys:
    driver: local
